### ISSUE TITLE
你好，请问雷达循迹如何解决遇到直角冲出地图的情况

### ISSUE THREAD

**Issue by wj-ss** [CodeAlanqian/2023ROS_Autocar#1]

**Comment by CodeAlanqian** [comment]
我们的当时的赛道没有直角弯元素，所以代码里面没有相关的特化处理。给你一个比较简单的思路：直角弯相对于起点的位置是已知的，你可以根据这个条件出发，当车到达直角弯范围的时候，另外让舵机多打点角度。当然这不够优雅，但是可行。

**Comment by Woo-wdy** [comment]
但是  坐标点好像不太准 怎么办

**Comment by Woo-wdy** [comment]
> 我们的当时的赛道没有直角弯元素，所以代码里面没有相关的特化处理。给你一个比较简单的思路：直角弯相对于起点的位置是已知的，你可以根据这个条件出发，当车到达直角弯范围的时候，另外让舵机多打点角度。当然这不够优雅，但是可行。

坐标点拐直角好像不太准确   好误判或者不拐

**Comment by CodeAlanqian** [comment]
那你参考这个：[laser_go](https://github.com/CodeAlanqian/2023ROS_Autocar/tree/main/%E5%AE%9E%E9%AA%8C%E6%BA%90%E7%A0%81/laser_go)
我们第一年（22年）参赛的时候是有直角弯元素的，但这个代码还不是很完善。

**Comment by Woo-wdy** [comment]
> 那你参考这个：[laser_go](https://github.com/CodeAlanqian/2023ROS_Autocar/tree/main/%E5%AE%9E%E9%AA%8C%E6%BA%90%E7%A0%81/laser_go) 我们第一年（22年）参赛的时候是有直角弯元素的，但这个代码还不是很完善。

但我用这个代码连基础的弯道也过不了

**Comment by CodeAlanqian** [comment]
调整一下参数
